apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "nagios.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nagios.name" . }}
    helm.sh/chart: {{ include "nagios.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nagios.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nagios.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
          - name: MAIL_RELAY_HOST
            value: "{{ .Values.mail.relay_host }}"
          - name: MAIL_INET_PROTOCOLS
            value: ipv4
          livenessProbe:
            exec:
              command:
              - cat
              - /etc/passwd
            initialDelaySeconds: 5
            periodSeconds: 5
            #httpGet:
            #  path: /robots.txt
            #  port: http
            #  httpHeaders:
            #  - name: Authorization
            #    value: Basic xyz
          readinessProbe:
            exec:
              command:
              - cat
              - /etc/passwd
            initialDelaySeconds: 5
            periodSeconds: 5
            #httpGet:
            #  path: /robots.txt
            #  port: http
            #  httpHeaders:
            #  - name: Authorization
            #    value: Basic xyz
        {{- with .Values.extraVolumeMounts }}
          volumeMounts:
{{ toYaml . | indent 12 }}
        {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.extraVolumes }}
      volumes:
{{ toYaml . | indent 8 }}
    {{- end }}
